######################################################################
# testing cases
library(car)
data(mydata)
m1 = lm(Depression ~  Fatalism + Sex + R_E + Age , data = mydata)
m2 = lm(Depression ~  -1 + Fatalism + Sex + R_E + Age , data = mydata)
m3 = lm(Depression ~  Fatalism + Sex + R_E + Age_4Cat + NIHSS_4Cat, data = mydata)
m4 = lm(Depression ~  Fatalism + Sex + R_E + factor(Age_4Cat) + factor(NIHSS_4Cat), data = mydata)
m5 = lm(Depression ~  -1 + Fatalism + Sex + R_E + factor(Age_4Cat) , data = mydata)
m6 = lm(Depression ~ Fatalism, data = mydata)
residualPlots(m6)
m7 = lm(Depression ~ -1 + Fatalism, data = mydata)
m8 = lm(Depression ~  Fatalism + Sex + R_E + Age + Age*Sex + Age*Fatalism + Age*Sex*Fatalism, data = mydata)
residualPlots(m7)
covar1 = c('Fatalism', 'Sex', 'R_E', 'Age')
covar2 = c('Fatalism', 'Sex', 'R_E', 'Age_4Cat', 'NIHSS_4Cat')
covar3 = c('Fatalism', 'Sex', 'R_E', 'Age_4Cat')
covar4 = c('Fatalism')
# Comorbidity1 could use 0 as ref, HiChol us 0
covar5 = c('Fatalism', 'Sex', 'R_E', 'Age', 'Optimism','Hospit','NIHSS_4Cat', 'Comorbidity1','HiChol')
t1 = mylm(mydata, 'Depression', covar1)
t2 = mylm(mydata, 'Depression', covar1, intercept = F)
t3 = mylm(mydata, 'Depression', covar2)
t4 = mylm(mydata, 'Depression', covar2, category = c('Age_4Cat', 'NIHSS_4Cat'), ref = c(1,1))
t5 = mylm(mydata, 'Depression', covar3, category = c('Age_4Cat'), cat_method = 'cellmeans', intercept = F)
t6 = mylm(mydata, 'Depression', covar4)
t7 = mylm(mydata, 'Depression', covar4, intercept = F)
t8 = mylm(mydata, 'Depression', covar1, inter = c('Age:Sex','Age:Fatalism','Age:Sex:Fatalism'))
test_set = subset(mydata, select = c(covar2,'Depression'))
categorize(mydata, c('R_E', 'NIHSS_4Cat'), ref = c(0,1))
categorize(mydata, c('R_E', 'NIHSS_4Cat'), method = 'cellmeans')
